const alternatives = [
    // --- SEARCH ENGINES ---
    {
        id: "qwant",
        name: "Qwant",
        category: "Search Engine",
        country: "France",
        description: "The search engine that respects your privacy. No tracking, no data selling.",
        link: "https://www.qwant.com",
        alternativeTo: "Google",
        pros: ["Does not track your search history", "Server hosted in Europe (France)", "Neutral search results"],
        cons: ["Search index smaller than Google's", "Maps features are less detailed", "Ads are still present (but non-targeted)"],
        ecoGrade: "B"
    },
    {
        id: "ecosia",
        name: "Ecosia",
        category: "Search Engine",
        country: "Germany",
        description: "The search engine that plants trees with its ad revenue.",
        link: "https://www.ecosia.org",
        alternativeTo: "Google",
        pros: ["Plants trees with revenue", "Privacy friendly", "Uses Bing index (reliable)"],
        cons: ["Search results not as rich as Google", "Depends on Bing", "Ads are present"],
        ecoGrade: "A"
    },
    {
        id: "startpage",
        name: "Startpage",
        category: "Search Engine",
        country: "Netherlands",
        description: "The world's most private search engine. It delivers Google results without tracking.",
        link: "https://www.startpage.com",
        alternativeTo: "Google",
        pros: ["Google quality results", "Absolute privacy (no logs)", "Anonymous view feature"],
        cons: ["Owned by an ad-tech company (System1) since 2019", "Slower than direct Google", "Design is basic"],
        ecoGrade: "B"
    },

    // --- AUTOMOTIVE ---
    {
        id: "peugeot",
        name: "Peugeot",
        category: "Automotive",
        country: "France",
        description: "Innovative French car manufacturer known for stylish designs and electric vehicles.",
        link: "https://www.peugeot.com",
        alternativeTo: "Toyota, Volkswagen",
        pros: ["Distinctive, modern design", "Wide range of Electric & Hybrid options", "i-Cockpit interior ergonomics"],
        cons: ["Higher price point than some competitors", "Infotainment software can be complex", "Maintenance costs"],
        ecoGrade: "C"
    },
    {
        id: "renault",
        name: "Renault",
        category: "Automotive",
        country: "France",
        description: "Historical French brand, pioneer in electric vehicles with the Zoe and new R5.",
        link: "https://www.renault.fr",
        alternativeTo: "Ford, Hyundai",
        pros: ["Strong EV lineup (Zoé, Megane E-Tech)", "Affordable city cars", "Wide service network"],
        cons: ["Interior plastic quality on cheaper models", "Reliability reputation varies", "Depreciation"],
        ecoGrade: "C"
    },
    {
        id: "volkswagen",
        name: "Volkswagen",
        category: "Automotive",
        country: "Germany",
        description: "The 'People's Car', Europe's largest car maker offering a massive range of vehicles.",
        link: "https://www.volkswagen.com",
        alternativeTo: "Toyota, GM",
        pros: ["Solid build quality", "Massive ID. electric range", "Intuitive driving dynamics"],
        cons: ["Software issues in early ID models", "Conservative styling", "Pricey options list"],
        ecoGrade: "C"
    },
    {
        id: "volvo",
        name: "Volvo",
        category: "Automotive",
        country: "Sweden",
        description: "Premium brand synonymous with safety, now transitioning to fully electric.",
        link: "https://www.volvocars.com",
        alternativeTo: "Audi, Lexus",
        pros: ["Industry leader in safety", "Minimalist Scandinavian design", "Committed to 100% electric by 2030"],
        cons: ["Speed limited to 180km/h on new models", "Expensive maintenance", "Owned by Geely (China)"],
        ecoGrade: "B"
    },
    {
        id: "fiat",
        name: "Fiat",
        category: "Automotive",
        country: "Italy",
        description: "Iconic Italian brand known for small city cars and the legendary 500.",
        link: "https://www.fiat.com",
        alternativeTo: "Mini, Smart",
        pros: ["Iconic design (Fiat 500)", "Perfect for city driving", "Affordable electric options"],
        cons: ["Limited range on highway", "Small interiors", "Build quality inconsistent"],
        ecoGrade: "B"
    },

    // --- SODA & DRINKS ---
    {
        id: "fritz-kola",
        name: "Fritz-kola",
        category: "Soda",
        country: "Germany",
        description: "Independent soda brand from Hamburg, known for high caffeine content and sustainable values.",
        link: "https://www.fritz-kola.com",
        alternativeTo: "Coca-Cola, Pepsi",
        pros: ["Glass bottles only (Reusable)", "High caffeine kick", "Vegan & natural"],
        cons: ["More expensive than big brands", "Harder to find outside cities", "Strong unique taste (love/hate)"],
        ecoGrade: "A"
    },
    {
        id: "breizh-cola",
        name: "Breizh Cola",
        category: "Soda",
        country: "France",
        description: "The Cola of Brittany. A regional success story with a unique caramel salted butter hint.",
        link: "https://www.breizhcola.fr",
        alternativeTo: "Coca-Cola",
        pros: ["Unique regional flavor", "Supports local economy", "Cheaper than craft colas"],
        cons: ["Very sugary", "Hard to find outside France", "Plastic bottles common"],
        ecoGrade: "C"
    },
    {
        id: "club-mate",
        name: "Club-Mate",
        category: "Soda",
        country: "Germany",
        description: "Cult caffeinated mate-extract beverage, favorite of hackers and clubbers.",
        link: "https://www.club-mate.de",
        alternativeTo: "Red Bull, Monster",
        pros: ["Natural caffeine boost", "Less sugar than energy drinks", "Iconic status"],
        cons: ["Acquired taste (herbal/smoky)", "Contains sugar", "Niche availability"],
        ecoGrade: "B"
    },
    {
        id: "rivella",
        name: "Rivella",
        category: "Soda",
        country: "Switzerland",
        description: "Swiss carbonated soft drink created from milk whey.",
        link: "https://www.rivella.com",
        alternativeTo: "Fanta, Sprite",
        pros: ["Uses food waste (milk whey)", "Unique refreshing taste", "National icon"],
        cons: ["Contains lactose (except some versions)", "Weird concept for foreigners", "Pricey"],
        ecoGrade: "B"
    },
    {
        id: "orangina",
        name: "Orangina",
        category: "Soda",
        country: "France",
        description: "Lightly carbonated beverage made from carbonated water, orange juice, and other citrus juices.",
        link: "https://orangina.eu",
        alternativeTo: "Fanta",
        pros: ["Real fruit pulp", "Less artificial than Fanta", "Iconic bottle"],
        cons: ["Owned by Suntory (Japan) now", "High sugar content", "Need to shake it"],
        ecoGrade: "C"
    },

    // --- FAST FOOD ---
    {
        id: "quick",
        name: "Quick",
        category: "Fast Food",
        country: "Belgium",
        description: "European fast food chain founded in Belgium, famous for the Giant burger.",
        link: "https://www.quick.fr",
        alternativeTo: "McDonald's, Burger King",
        pros: ["The 'Giant' sauce is legendary", "Halal options widely available", "European heritage"],
        cons: ["Nutritional quality is low", "Often dirtier than competitors", "Declining number of restaurants"],
        ecoGrade: "E"
    },
    {
        id: "hesburger",
        name: "Hesburger",
        category: "Fast Food",
        country: "Finland",
        description: "Largest fast food chain in Finland and the Baltics, known for its mayonnaise.",
        link: "https://www.hesburger.com",
        alternativeTo: "McDonald's",
        pros: ["Unique mayonnaise recipes", "More salads/vegetarian options", "Cozy interior design"],
        cons: ["Aggressive expansion", "Processed food", "Single-use packaging"],
        ecoGrade: "D"
    },
    {
        id: "nordsee",
        name: "Nordsee",
        category: "Fast Food",
        country: "Germany",
        description: "Fast-food chain specialising in seafood.",
        link: "https://www.nordsee.com",
        alternativeTo: "Long John Silver's",
        pros: ["Healthier than burger chains", "Fresh fish options", "Plate service available"],
        cons: ["Overfishing concerns", "More expensive", "Fried options are heavy"],
        ecoGrade: "D"
    },
    {
        id: "max-burgers",
        name: "MAX Burgers",
        category: "Fast Food",
        country: "Sweden",
        description: "Oldest burger chain in Sweden, pioneering climate-positive burgers.",
        link: "https://www.max.se",
        alternativeTo: "Burger King",
        pros: ["Climate positive menu", "Great vegetarian 'Green' range", "Premium taste"],
        cons: ["More expensive", "Slower service", "Limited to Northern Europe"],
        ecoGrade: "B"
    },
    {
        id: "otacos",
        name: "O'Tacos",
        category: "Fast Food",
        country: "France",
        description: "French fast food chain serving 'French Tacos'.",
        link: "https://o-tacos.com",
        alternativeTo: "Taco Bell, Chipotle",
        pros: ["Huge portion sizes", "Fully customizable", "Cheap calories"],
        cons: ["Extremely unhealthy (cheese sauce)", "Not authentic tacos", "Heavy feeling after eating"],
        ecoGrade: "E"
    },

    // --- FASHION & MODE ---
    {
        id: "veja",
        name: "Veja",
        category: "Fashion",
        country: "France",
        description: "Ecological and fair trade footwear brand.",
        link: "https://www.veja-store.com",
        alternativeTo: "Nike, Adidas, Stan Smith",
        pros: ["Fair trade rubber/cotton", "Transparent supply chain", "Trendy minimalist design"],
        cons: ["Leather can be stiff initially", "Pricey for basics", "Not suitable for running/sport"],
        ecoGrade: "A"
    },
    {
        id: "armedangels",
        name: "ARMEDANGELS",
        category: "Fashion",
        country: "Germany",
        description: "Contemporary fashion brand that loves beautiful products and hates cheap manufacturing.",
        link: "https://www.armedangels.com",
        alternativeTo: "H&M, Zara",
        pros: ["GOTS certified organic cotton", "Fair Wear Foundation member", "Timeless designs"],
        cons: ["More expensive than fast fashion", "Limited physical stores", "Slower trend cycle"],
        ecoGrade: "A"
    },
    {
        id: "nudie-jeans",
        name: "Nudie Jeans",
        category: "Fashion",
        country: "Sweden",
        description: "Sustainable denim brand offering free repairs for life.",
        link: "https://www.nudiejeans.com",
        alternativeTo: "Levi's, Diesel",
        pros: ["Free repairs forever", "100% organic cotton", "Transparent production"],
        cons: ["High upfront cost", "Raw denim needs breaking in", "Specific style (slim fits)"],
        ecoGrade: "A"
    },
    {
        id: "decathlon",
        name: "Decathlon",
        category: "Sportswear",
        country: "France",
        description: "The world's largest sporting goods retailer, designing and selling its own brands.",
        link: "https://www.decathlon.com",
        alternativeTo: "Dick's Sporting Goods, Foot Locker",
        pros: ["Unbeatable price/quality ratio", "Innovation in R&D", "Covers every sport possible"],
        cons: ["Fast fashion business model", "Variable durability on entry range", "Ubiquitous/Generic"],
        ecoGrade: "C"
    },
    {
        id: "vinted",
        name: "Vinted",
        category: "Fashion",
        country: "Lithuania",
        description: "Online marketplace for buying, selling and exchanging new or secondhand items.",
        link: "https://www.vinted.com",
        alternativeTo: "Shein, Temu (by buying used)",
        pros: ["Promotes circular economy", "Cheap finds", "Easy to sell"],
        cons: ["Buyer protection fees", "Risk of scams", "Shipping creates carbon footprint"],
        ecoGrade: "A"
    },

    // --- TECH & APPS ---
    {
        id: "deezer",
        name: "Deezer",
        category: "Music Streaming",
        country: "France",
        description: "Music streaming service with over 90 million tracks.",
        link: "https://www.deezer.com",
        alternativeTo: "Spotify, Apple Music",
        pros: ["High Fidelity (HiFi) audio quality included", "Excellent 'Flow' recommendation algorithm", "Lyrics integration"],
        cons: ["Free tier contains ads", "Mobile app interface can be cluttered", "Smaller podcast library than Spotify"],
        ecoGrade: "C"
    },
    {
        id: "spotify",
        name: "Spotify",
        category: "Music Streaming",
        country: "Sweden",
        description: "Digital music service that gives you access to millions of songs.",
        link: "https://www.spotify.com",
        alternativeTo: "Apple Music",
        pros: ["Best-in-class discovery algorithms", "Huge device compatibility (Connect)", "Massive user community playlists"],
        cons: ["Pays artists less than competitors", "HiFi audio still missing", "Aggressive podcast promotion"],
        ecoGrade: "C"
    },
    {
        id: "protonmail",
        name: "Proton",
        category: "Email",
        country: "Switzerland",
        description: "Secure email, calendar, and drive based in Switzerland.",
        link: "https://proton.me",
        alternativeTo: "Gmail, Google Drive",
        pros: ["End-to-end encryption", "Based in Switzerland (Strict privacy laws)", "Open source cryptography"],
        cons: ["Free storage is limited", "No proprietary search scanning (privacy trade-off)", "Recovery is hard"],
        ecoGrade: "A"
    },
    {
        id: "tuta",
        name: "Tuta",
        category: "Email",
        country: "Germany",
        description: "Secure email service with a focus on simplicity and green energy.",
        link: "https://tuta.com",
        alternativeTo: "Gmail",
        pros: ["Runs on 100% renewable energy", "Encrypts subject lines too", "Very affordable"],
        cons: ["No IMAP support (security decision)", "UI is utilitarian", "Smaller ecosystem than Proton"],
        ecoGrade: "A"
    },
    {
        id: "telegram",
        name: "Telegram",
        category: "Messaging",
        country: "Germany/UAE",
        description: "Cloud-based mobile and desktop messaging app.",
        link: "https://telegram.org",
        alternativeTo: "WhatsApp",
        pros: ["Extremely fast", "Cloud sync across all devices", "Huge group limits"],
        cons: ["Not E2E encrypted by default", "Metadata collection", "Cloud storage concerns"],
        ecoGrade: "B"
    },
    {
        id: "threema",
        name: "Threema",
        category: "Messaging",
        country: "Switzerland",
        description: "The world's best-selling secure messenger.",
        link: "https://threema.ch",
        alternativeTo: "WhatsApp",
        pros: ["No phone number required", "Swiss laws protection", "One-time fee (No ads)"],
        cons: ["Paid app (barrier to entry)", "Smaller userbase", "No cloud history"],
        ecoGrade: "A"
    },
    {
        id: "wire",
        name: "Wire",
        category: "Messaging",
        country: "Germany/CH",
        description: "Secure collaboration platform with end-to-end encryption.",
        link: "https://wire.com",
        alternativeTo: "Slack, WhatsApp",
        pros: ["Great for enterprise", "Multi-device E2E encryption", "Open source"],
        cons: ["Metadata storage on servers", "Can be buggy", "Focus shifted to B2B"],
        ecoGrade: "B"
    },
    {
        id: "vlc",
        name: "VLC",
        category: "Software",
        country: "France",
        description: "Free and open source cross-platform multimedia player.",
        link: "https://www.videolan.org",
        alternativeTo: "Windows Media Player",
        pros: ["Plays absolutely everything", "No ads, no tracking", "Lightweight"],
        cons: ["UI is dated", "Library management is basic", "Complex menus"],
        ecoGrade: "A"
    },
    {
        id: "blender",
        name: "Blender",
        category: "3D Software",
        country: "Netherlands",
        description: "Free and open source 3D creation suite.",
        link: "https://www.blender.org",
        alternativeTo: "Maya, 3ds Max",
        pros: ["Completely free", "All-in-one suite", "Rapid innovation"],
        cons: ["Steep learning curve", "Industry adoption still growing", "UI complex"],
        ecoGrade: "A"
    },
    {
        id: "deepl",
        name: "DeepL",
        category: "Translation",
        country: "Germany",
        description: "The world's most accurate translator.",
        link: "https://www.deepl.com",
        alternativeTo: "Google Translate",
        pros: ["Better nuance than Google", "Document translation", "Strict data privacy (Pro)"],
        cons: ["Fewer languages", "Free limits", "No website widget"],
        ecoGrade: "B"
    },
    {
        id: "nextcloud",
        name: "Nextcloud",
        category: "Cloud Storage",
        country: "Germany",
        description: "Self-hosted productivity platform that keeps you in control.",
        link: "https://nextcloud.com",
        alternativeTo: "Google Drive, Dropbox",
        pros: ["Total data sovereignty", "Huge app ecosystem", "GDPR compliant"],
        cons: ["Self-hosting is technical", "Managed hosting costs money", "Sync conflicts possible"],
        ecoGrade: "A"
    },
    {
        id: "ovhcloud",
        name: "OVHcloud",
        category: "Web Hosting",
        country: "France",
        description: "Global cloud computing player, #1 in Europe.",
        link: "https://www.ovhcloud.com",
        alternativeTo: "AWS, Google Cloud",
        pros: ["Data in Europe (GDPR)", "Competitive pricing", "Anti-DDoS expertise"],
        cons: ["Support often criticized", "Dashboard UI complex", "Variable network speeds"],
        ecoGrade: "B"
    },
    {
        id: "scaleway",
        name: "Scaleway",
        category: "Web Hosting",
        country: "France",
        description: "The cloud that makes sense. Multi-cloud provider.",
        link: "https://www.scaleway.com",
        alternativeTo: "DigitalOcean, AWS",
        pros: ["Modern UI/UX", "Innovative hardware (ARM, RISC-V)", "Green data center emphasis"],
        cons: ["Smaller feature set than AWS", "Support response times", "Price increases"],
        ecoGrade: "A"
    },
    {
        id: "fairphone",
        name: "Fairphone",
        category: "Hardware",
        country: "Netherlands",
        description: "The smartphone that cares for people and planet.",
        link: "https://www.fairphone.com",
        alternativeTo: "iPhone, Galaxy",
        pros: ["Repairable by design (DIY)", "Conflict-free materials", "5-year warranty"],
        cons: ["Bulky design", "Mid-range specs for high price", "Camera quality varies"],
        ecoGrade: "A"
    },
    {
        id: "sap",
        name: "SAP",
        category: "Enterprise Software",
        country: "Germany",
        description: "Market leader in enterprise application software.",
        link: "https://www.sap.com",
        alternativeTo: "Salesforce, Oracle",
        pros: ["Standard for large corps", "Comprehensive suite", "Scalable"],
        cons: ["Extremely expensive", "Old-school UI in parts", "Implementation nightmare"],
        ecoGrade: "C"
    },
    {
        id: "dailymotion",
        name: "Dailymotion",
        category: "Video Sharing",
        country: "France",
        description: "Video-sharing technology platform and video player.",
        link: "https://www.dailymotion.com",
        alternativeTo: "YouTube",
        pros: ["Less censorship/takedowns", "Cleaner player", "European legal framework"],
        cons: ["Content library smaller", "Aggressive ads on free view", "Lower max resolution often"],
        ecoGrade: "D"
    },
    {
        id: "mastodon",
        name: "Mastodon",
        category: "Social Media",
        country: "Germany",
        description: "Decentralized, open-source social network server.",
        link: "https://joinmastodon.org",
        alternativeTo: "Twitter (X)",
        pros: ["No algorithmic manipulation", "Ad-free", "No single owner"],
        cons: ["Confusing signup", "Fragmented network", "Discoverability is harder"],
        ecoGrade: "A"
    },

    // --- TRAVEL & TRANSPORT ---
    {
        id: "blablacar",
        name: "BlaBlaCar",
        category: "Travel",
        country: "France",
        description: "World's leading long-distance carpooling community.",
        link: "https://www.blablacar.com",
        alternativeTo: "Uber (Long distance), Trains",
        pros: ["Very cheap travel", "Social experience", "Reduces carbon footprint"],
        cons: ["Relies on driver punctuality", "Awkward conversations", "Last minute cancellations"],
        ecoGrade: "A"
    },
    {
        id: "bolt",
        name: "Bolt",
        category: "Mobility",
        country: "Estonia",
        description: "The European super-app for ride-hailing and scooters.",
        link: "https://bolt.eu",
        alternativeTo: "Uber",
        pros: ["Usually cheaper than Uber", "Carbon neutral rides", "Fast pickups"],
        cons: ["Variable driver quality", "Surge pricing", "App glitches"],
        ecoGrade: "C"
    },
    {
        id: "flixbus",
        name: "FlixBus",
        category: "Travel",
        country: "Germany",
        description: "Low-cost bus travel across Europe and the US.",
        link: "https://www.flixbus.com",
        alternativeTo: "Greyhound, Trains",
        pros: ["Unbeatable prices", "Huge network", "Modern buses with Wi-Fi"],
        cons: ["Slow travel times", "Cramped seats", "Delays common"],
        ecoGrade: "B"
    },
    {
        id: "booking",
        name: "Booking.com",
        category: "Travel",
        country: "Netherlands",
        description: "One of the largest travel e-commerce companies in the world.",
        link: "https://www.booking.com",
        alternativeTo: "Airbnb, Expedia",
        pros: ["Massive selection", "genius loyalty program", "Transparent reviews"],
        cons: ["High commissions for hotels", "Pressure tactics (Only 1 room left!)", "Customer service automation"],
        ecoGrade: "C"
    },
    {
        id: "skyscanner",
        name: "Skyscanner",
        category: "Travel",
        country: "UK",
        description: "Travel search engine for flights, hotels and car hire.",
        link: "https://www.skyscanner.net",
        alternativeTo: "Google Flights, Kayak",
        pros: ["Finds the cheapest dates", "Includes budget airlines", "Unbiased comparison"],
        cons: ["Redirects to shady OTAs sometimes", "Prices can change on click", "Owned by Trip.com (China) now"],
        ecoGrade: "C"
    },
    {
        id: "trainline",
        name: "Trainline",
        category: "Travel",
        country: "UK",
        description: "Europe's leading train and coach app.",
        link: "https://www.thetrainline.com",
        alternativeTo: "Official Rail Apps",
        pros: ["Great UI/UX", "Split-ticket savings", "Cross-border booking"],
        cons: ["Booking fees apply", "Refunds can be tricky", "Data collection"],
        ecoGrade: "B"
    },

    // --- OTHER ---
    {
        id: "libreoffice",
        name: "LibreOffice",
        category: "Productivity",
        country: "Germany",
        description: "Free and open-source office suite.",
        link: "https://www.libreoffice.org",
        alternativeTo: "Microsoft Office",
        pros: ["Free forever", "Supports all formats", "No cloud dependency"],
        cons: ["UI looks antiquated", "Collaboration features weak", "Formatting glitches with Word"],
        ecoGrade: "A"
    },
    {
        id: "arduino",
        name: "Arduino",
        category: "Hardware",
        country: "Italy",
        description: "Open-source electronics platform based on easy-to-use hardware and software.",
        link: "https://www.arduino.cc",
        alternativeTo: "Raspberry Pi (UK), Proprietary Chips",
        pros: ["Huge learning community", "Simple to code", "Inexpensive"],
        cons: ["Limited processing power", "Not a full OS computer", "Clones are everywhere"],
        ecoGrade: "A"
    }

];
